key:
    password: "There cAn bE onLy ONE"
    secret_key: "r.H97m3T(o6nAbl^qm'QOd+|`n4wB["
db:
    type: "mysql"
    host: "192.168.1.245"
    name: "prod_audit"
    user: "doug"
    pass: "9Etr8F*uBr"
    charset: "utf8"
    